export const COMPANY_FETCH_REQUEST = "COMPANY_FETCH_REQUEST"
export const COMPANY_FETCH_SUCCESS = "COMPANY_FETCH_SUCCESS"
export const COMPANY_FETCH_FAILURE = "COMPANY_FETCH_FAILURE"

export const USER_FETCH_REQUEST = "USER_FETCH_REQUEST"
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS"
export const USER_FETCH_FAILURE = "USER_FETCH_FAILURE"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const LOGIN_RESET = "LOGIN_RESET";